/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef REQUIREDDISKSPACEUSAGE_H
#define REQUIREDDISKSPACEUSAGE_H

/* function declarations */
void init_requiredDiskSpaceUsage(void);
Netsnmp_Node_Handler handle_requiredDiskSpaceUsage;

#endif /* REQUIREDDISKSPACEUSAGE_H */
