/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef SNMPSIGNAL_H
#define SNMPSIGNAL_H

/* function declarations */
void init_snmpSignal(void);
Netsnmp_Node_Handler handle_snmpSignal;

#endif /* SNMPSIGNAL_H */
