/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef STATICPROGRAMMEVERSION_H
#define STATICPROGRAMMEVERSION_H

/* function declarations */
void init_staticProgrammeVersion(void);
Netsnmp_Node_Handler handle_staticProgrammeVersion;

#endif /* STATICPROGRAMMEVERSION_H */
